[project]
name = "civic-services-pilot"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Francesco Piras", email = "pirassao97@gmail.com" }
]
requires-python = ">=3.14"
dependencies = [
    "arize-phoenix>=20.14.0",
    "arize-phoenix-otel>=0.17.1",
    "openai>=3.15.0",
    "openinference-instrumentation-openai>=0.1.60",
    "python-dotenv>=1.2.3",
]

[project.scripts]
civic-services-pilot = "civic_services_pilot:main"

[build-system]
requires = ["uv_build>=0.12.13,<0.13.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "pytest>=9.1.1",
]
